/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'sender' : string,
  'timestamp' : Timestamp,
}
export interface CoachSelection {
  'selectedCoachId' : bigint,
  'userId' : UserId,
}
export interface DietLog {
  'id' : bigint,
  'fat' : bigint,
  'meals' : Array<string>,
  'carbs' : bigint,
  'userId' : UserId,
  'date' : Timestamp,
  'calories' : bigint,
  'protein' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface HabitTracker {
  'completedDays' : Array<Timestamp>,
  'workoutSchedule' : Array<string>,
  'userId' : UserId,
  'streakCount' : bigint,
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'age' : bigint,
  'bmi' : number,
  'weight' : bigint,
  'height' : bigint,
  'fitnessGoals' : Array<string>,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkoutSession {
  'id' : bigint,
  'performanceScore' : bigint,
  'userId' : UserId,
  'date' : Timestamp,
  'reps' : bigint,
  'exercise' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__fitnessState' : ActorMethod<[], any>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChatMessage' : ActorMethod<[ChatMessage], bigint>,
  'createCoachSelection' : ActorMethod<[UserId, CoachSelection], undefined>,
  'createDietLog' : ActorMethod<[DietLog], bigint>,
  'createHabitTracker' : ActorMethod<[UserId, HabitTracker], undefined>,
  'createUserProfile' : ActorMethod<[UserProfile], undefined>,
  'createWorkoutSession' : ActorMethod<[WorkoutSession], bigint>,
  'deleteChatMessage' : ActorMethod<[bigint], undefined>,
  'deleteCoachSelection' : ActorMethod<[UserId], undefined>,
  'deleteDietLog' : ActorMethod<[bigint], undefined>,
  'deleteHabitTracker' : ActorMethod<[UserId], undefined>,
  'deleteUserProfile' : ActorMethod<[UserId], undefined>,
  'deleteWorkoutSession' : ActorMethod<[bigint], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessage' : ActorMethod<[bigint], [] | [ChatMessage]>,
  'getCoachSelection' : ActorMethod<[UserId], [] | [CoachSelection]>,
  'getDietLog' : ActorMethod<[bigint], [] | [DietLog]>,
  'getHabitTracker' : ActorMethod<[UserId], [] | [HabitTracker]>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getWorkoutSession' : ActorMethod<[bigint], [] | [WorkoutSession]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'listDietLogsByUser' : ActorMethod<[UserId], Array<DietLog>>,
  'listWorkoutSessionsByUser' : ActorMethod<[UserId], Array<WorkoutSession>>,
  'sendVirtualGymBuddyMessage' : ActorMethod<[string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCoachSelection' : ActorMethod<[UserId, CoachSelection], undefined>,
  'updateDietLog' : ActorMethod<[bigint, DietLog], undefined>,
  'updateHabitTracker' : ActorMethod<[UserId, HabitTracker], undefined>,
  'updateUserProfile' : ActorMethod<[UserId, UserProfile], undefined>,
  'updateWorkoutSession' : ActorMethod<[bigint, WorkoutSession], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];