/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Nat;
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : Timestamp,
});
export const UserId = IDL.Principal;
export const CoachSelection = IDL.Record({
  'selectedCoachId' : IDL.Nat,
  'userId' : UserId,
});
export const DietLog = IDL.Record({
  'id' : IDL.Nat,
  'fat' : IDL.Nat,
  'meals' : IDL.Vec(IDL.Text),
  'carbs' : IDL.Nat,
  'userId' : UserId,
  'date' : Timestamp,
  'calories' : IDL.Nat,
  'protein' : IDL.Nat,
});
export const HabitTracker = IDL.Record({
  'completedDays' : IDL.Vec(Timestamp),
  'workoutSchedule' : IDL.Vec(IDL.Text),
  'userId' : UserId,
  'streakCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'bmi' : IDL.Float64,
  'weight' : IDL.Nat,
  'height' : IDL.Nat,
  'fitnessGoals' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
});
export const WorkoutSession = IDL.Record({
  'id' : IDL.Nat,
  'performanceScore' : IDL.Nat,
  'userId' : UserId,
  'date' : Timestamp,
  'reps' : IDL.Nat,
  'exercise' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__fitnessState' : IDL.Func([], [IDL.Reserved], ['query']),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChatMessage' : IDL.Func([ChatMessage], [IDL.Nat], []),
  'createCoachSelection' : IDL.Func([UserId, CoachSelection], [], []),
  'createDietLog' : IDL.Func([DietLog], [IDL.Nat], []),
  'createHabitTracker' : IDL.Func([UserId, HabitTracker], [], []),
  'createUserProfile' : IDL.Func([UserProfile], [], []),
  'createWorkoutSession' : IDL.Func([WorkoutSession], [IDL.Nat], []),
  'deleteChatMessage' : IDL.Func([IDL.Nat], [], []),
  'deleteCoachSelection' : IDL.Func([UserId], [], []),
  'deleteDietLog' : IDL.Func([IDL.Nat], [], []),
  'deleteHabitTracker' : IDL.Func([UserId], [], []),
  'deleteUserProfile' : IDL.Func([UserId], [], []),
  'deleteWorkoutSession' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessage' : IDL.Func([IDL.Nat], [IDL.Opt(ChatMessage)], ['query']),
  'getCoachSelection' : IDL.Func(
      [UserId],
      [IDL.Opt(CoachSelection)],
      ['query'],
    ),
  'getDietLog' : IDL.Func([IDL.Nat], [IDL.Opt(DietLog)], ['query']),
  'getHabitTracker' : IDL.Func([UserId], [IDL.Opt(HabitTracker)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getWorkoutSession' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(WorkoutSession)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'listDietLogsByUser' : IDL.Func([UserId], [IDL.Vec(DietLog)], ['query']),
  'listWorkoutSessionsByUser' : IDL.Func(
      [UserId],
      [IDL.Vec(WorkoutSession)],
      ['query'],
    ),
  'sendVirtualGymBuddyMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCoachSelection' : IDL.Func([UserId, CoachSelection], [], []),
  'updateDietLog' : IDL.Func([IDL.Nat, DietLog], [], []),
  'updateHabitTracker' : IDL.Func([UserId, HabitTracker], [], []),
  'updateUserProfile' : IDL.Func([UserId, UserProfile], [], []),
  'updateWorkoutSession' : IDL.Func([IDL.Nat, WorkoutSession], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Nat;
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const UserId = IDL.Principal;
  const CoachSelection = IDL.Record({
    'selectedCoachId' : IDL.Nat,
    'userId' : UserId,
  });
  const DietLog = IDL.Record({
    'id' : IDL.Nat,
    'fat' : IDL.Nat,
    'meals' : IDL.Vec(IDL.Text),
    'carbs' : IDL.Nat,
    'userId' : UserId,
    'date' : Timestamp,
    'calories' : IDL.Nat,
    'protein' : IDL.Nat,
  });
  const HabitTracker = IDL.Record({
    'completedDays' : IDL.Vec(Timestamp),
    'workoutSchedule' : IDL.Vec(IDL.Text),
    'userId' : UserId,
    'streakCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'bmi' : IDL.Float64,
    'weight' : IDL.Nat,
    'height' : IDL.Nat,
    'fitnessGoals' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
  });
  const WorkoutSession = IDL.Record({
    'id' : IDL.Nat,
    'performanceScore' : IDL.Nat,
    'userId' : UserId,
    'date' : Timestamp,
    'reps' : IDL.Nat,
    'exercise' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__fitnessState' : IDL.Func([], [IDL.Reserved], ['query']),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChatMessage' : IDL.Func([ChatMessage], [IDL.Nat], []),
    'createCoachSelection' : IDL.Func([UserId, CoachSelection], [], []),
    'createDietLog' : IDL.Func([DietLog], [IDL.Nat], []),
    'createHabitTracker' : IDL.Func([UserId, HabitTracker], [], []),
    'createUserProfile' : IDL.Func([UserProfile], [], []),
    'createWorkoutSession' : IDL.Func([WorkoutSession], [IDL.Nat], []),
    'deleteChatMessage' : IDL.Func([IDL.Nat], [], []),
    'deleteCoachSelection' : IDL.Func([UserId], [], []),
    'deleteDietLog' : IDL.Func([IDL.Nat], [], []),
    'deleteHabitTracker' : IDL.Func([UserId], [], []),
    'deleteUserProfile' : IDL.Func([UserId], [], []),
    'deleteWorkoutSession' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessage' : IDL.Func([IDL.Nat], [IDL.Opt(ChatMessage)], ['query']),
    'getCoachSelection' : IDL.Func(
        [UserId],
        [IDL.Opt(CoachSelection)],
        ['query'],
      ),
    'getDietLog' : IDL.Func([IDL.Nat], [IDL.Opt(DietLog)], ['query']),
    'getHabitTracker' : IDL.Func([UserId], [IDL.Opt(HabitTracker)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getWorkoutSession' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(WorkoutSession)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'listDietLogsByUser' : IDL.Func([UserId], [IDL.Vec(DietLog)], ['query']),
    'listWorkoutSessionsByUser' : IDL.Func(
        [UserId],
        [IDL.Vec(WorkoutSession)],
        ['query'],
      ),
    'sendVirtualGymBuddyMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCoachSelection' : IDL.Func([UserId, CoachSelection], [], []),
    'updateDietLog' : IDL.Func([IDL.Nat, DietLog], [], []),
    'updateHabitTracker' : IDL.Func([UserId, HabitTracker], [], []),
    'updateUserProfile' : IDL.Func([UserId, UserProfile], [], []),
    'updateWorkoutSession' : IDL.Func([IDL.Nat, WorkoutSession], [], []),
  });
};

export const init = ({ IDL }) => { return []; };